# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='Ip')),
                ('visit_day', models.DateField()),
            ],
            options={
                'ordering': ['-visit_day'],
                'verbose_name': 'VisitIp',
            },
        ),
        migrations.CreateModel(
            name='VisitPv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=64, verbose_name='Ip')),
                ('visit_day', models.DateField()),
            ],
            options={
                'ordering': ['-visit_day'],
                'verbose_name': 'VisitPv',
            },
        ),
    ]
