# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitUv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv', models.IntegerField(verbose_name='uv_numbers')),
                ('visit_day', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='visitpv',
            options={},
        ),
        migrations.RemoveField(
            model_name='visitpv',
            name='page',
        ),
        migrations.AddField(
            model_name='visitip',
            name='visit_times',
            field=models.IntegerField(blank=True, default=1, verbose_name='visit_times_of_one_ip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitpv',
            name='pv',
            field=models.IntegerField(default=1, verbose_name='pv_numbers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitip',
            name='visit_day',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visitpv',
            name='visit_day',
            field=models.DateField(auto_now=True),
        ),
    ]
