# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pub_time',
            field=models.DateField(blank=True, default=b'2017-09-17'),
        ),
    ]
