# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-21 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170917_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
