# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.CharField(default='http://blog-1251509264.costj.myqcloud.com/defaultimg.jpg', max_length=255)),
                ('abstract', models.CharField(max_length=255)),
                ('article_url', models.CharField(max_length=100)),
                ('figure_type', models.CharField(choices=[('effect-chico', 'chico'), ('effect-milo', 'milo'), ('effect-roxy', 'roxy'), ('effect-marley', 'marley'), ('effect-sarah', 'sarah'), ('effect-bubba', 'bubba'), ('effect-lily', 'lily'), ('effect-layla', 'layla'), ('effect-oscar', 'oscar'), ('effect-honey', 'honey'), ('effect-zoe', 'zoe'), ('effect-romeo', 'romeo'), ('effect-sadie', 'sadie')], default='effect-layla', max_length=20)),
                ('trip_date', models.DateField()),
            ],
            options={
                'ordering': ['-trip_date'],
                'get_latest_by': 'trip_date',
                'verbose_name': '\u65c5\u6e38\u8bb0\u5f55',
            },
        ),
    ]
