# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-23 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20170921_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='figure_type',
            field=models.CharField(choices=[('effect-chico', 'chico'), ('effect-milo', 'milo'), ('effect-roxy', 'roxy'), ('effect-marley', 'marley'), ('effect-sarah', 'sarah'), ('effect-bubba', 'bubba'), ('effect-lily', 'lily'), ('effect-layla', 'layla'), ('effect-oscar', 'oscar'), ('effect-honey', 'honey'), ('effect-zoe', 'zoe'), ('effect-romeo', 'romeo'), ('effect-sadie', 'sadie')], default='effect-marley', max_length=20),
        ),
    ]
