# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(default='/static/img/hbnn.ico', upload_to=b'')),
                ('name', models.CharField(default='guest', max_length=48)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_article_name', to='blog.Article', verbose_name='\u539f\u6587\u540d\u5b57')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_comment_author', to='comment.Author')),
            ],
            options={
                'ordering': ['-create_time'],
                'get_latest_by': 'create_time',
                'verbose_name': 'comment',
            },
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment_author', to='comment.Author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='comment.Comment')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_author', to='comment.Author')),
            ],
            options={
                'ordering': ['create_time'],
                'get_latest_by': 'create_time',
                'verbose_name': 'replycomment',
            },
        ),
    ]
