# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-29 08:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='\u6807\u9898')),
                ('alias', models.CharField(max_length=150, verbose_name='\u82f1\u6587\u6807\u9898')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u6b63\u6587')),
                ('content_html', models.TextField(blank=True, verbose_name='\u6b63\u6587html\u683c\u5f0f')),
                ('abstract', models.TextField(blank=True, verbose_name='\u6458\u8981')),
                ('read_times', models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u6b21\u6570')),
                ('tags', models.CharField(help_text='\u7528\u9017\u53f7\u9694\u5f00', max_length=100, verbose_name='\u6807\u7b7e')),
                ('status', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u8349\u7a3f'), (2, '\u5220\u9664')], default=0, verbose_name='\u6587\u7ae0\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pub_time', models.DateTimeField(default=datetime.datetime(2017, 9, 29, 16, 11, 49, 917074))),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('access', models.IntegerField(choices=[(200, '\u79c1\u4eba\u53ef\u89c1'), (100, '\u516c\u5f00')], default=100, verbose_name='\u6587\u7ae0\u6743\u9650\uff0c\u516c\u5f00\u6216\u8005\u79c1\u4eba\u53ef\u89c1')),
                ('qrcode', models.IntegerField(default=0, verbose_name='\u4e8c\u7ef4\u7801\u72b6\u6001')),
                ('qrcode_url', models.CharField(max_length=255, unique=True, verbose_name='\u4e8c\u7ef4\u7801\u94fe\u63a5')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-create_time'],
                'get_latest_by': 'create_time',
                'verbose_name': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='\u7c7b\u540d')),
                ('alias', models.CharField(max_length=150, verbose_name='\u82f1\u6587\u540d\u79f0')),
                ('status', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u8349\u7a3f'), (2, '\u5220\u9664')], default=0, verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u4e0a\u7ea7\u5206\u7c7b')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u6587\u7ae0\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='OnlineArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6b63\u6587')),
                ('author_info', models.CharField(max_length=255, verbose_name='\u4f5c\u8005\u4fe1\u606f')),
                ('category', models.CharField(max_length=255, verbose_name='\u7c7b\u522b')),
                ('url', models.CharField(default='http://dailyblog.applinzi.com', max_length=255, verbose_name='\u94fe\u63a5')),
                ('finish', models.IntegerField(default=0, verbose_name='\u8f6c\u8f7d\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u5728\u7ebf\u597d\u6587',
            },
        ),
        migrations.CreateModel(
            name='WeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='\u6807\u9898')),
                ('desc', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('url', models.CharField(max_length=512, verbose_name='\u94fe\u63a5')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('finish', models.IntegerField(default=0, verbose_name='\u8f6c\u8f7d\u72b6\u6001')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u5fae\u4fe1\u6587\u7ae0',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u5206\u7c7b'),
        ),
    ]
