# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-24 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170924_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 13, 16, 51, 152271)),
        ),
    ]
