# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 16, 24, 53, 323000)),
        ),
    ]
