# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 03:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160425_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='\u6b63\u6587html\u683c\u5f0f'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 11, 29, 25, 208000)),
        ),
    ]
