# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160512_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='\u7c7b\u540d')),
                ('alias', models.CharField(max_length=150, verbose_name='\u82f1\u6587\u540d\u79f0')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 11, 10, 2, 880000)),
        ),
    ]
