# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='\u5730\u5740')),
                ('introduction', models.TextField(blank=True, verbose_name='\u4ecb\u7ecd')),
                ('homepage', models.CharField(blank=True, max_length=255, verbose_name='\u516c\u53f8\u4e3b\u9875')),
            ],
            options={
                'verbose_name': '\u516c\u53f8',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u804c\u4f4d\u540d\u79f0')),
                ('welfare', models.CharField(blank=True, max_length=255, verbose_name='\u798f\u5229')),
                ('requirement', models.TextField(blank=True, verbose_name='\u804c\u4f4d\u8981\u6c42')),
                ('link', models.CharField(max_length=255, verbose_name='\u94fe\u63a5')),
                ('pub_time', models.DateField(blank=True, default=b'2017-09-27')),
                ('load_time', models.DateTimeField(auto_now=True)),
                ('salary', models.CharField(blank=True, max_length=127, verbose_name='\u85aa\u8d44')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Company', verbose_name='\u516c\u53f8')),
            ],
            options={
                'db_table': 'job_detail',
                'verbose_name': '\u5de5\u4f5c\u804c\u4f4d',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255, unique=True, verbose_name='\u7f51\u7ad9')),
                ('homepage', models.CharField(max_length=255, verbose_name='\u4e3b\u9875')),
            ],
            options={
                'verbose_name': '\u62db\u8058\u5730\u5740',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Website', verbose_name='\u62db\u8058\u7f51\u7ad9'),
        ),
    ]
