# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-02 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pub_time',
            field=models.DateField(blank=True, default=b'2017-11-02'),
        ),
        migrations.AlterField(
            model_name='job',
            name='welfare',
            field=models.TextField(blank=True, verbose_name='\u798f\u5229'),
        ),
    ]
