# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160425_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 19, 44, 0, 926000)),
        ),
    ]
