# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160426_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='access',
            field=models.IntegerField(choices=[(200, '\u79c1\u4eba\u53ef\u89c1'), (100, '\u516c\u5f00')], default=100, verbose_name='\u6587\u7ae0\u6743\u9650\uff0c\u516c\u5f00\u6216\u8005\u79c1\u4eba\u53ef\u89c1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 20, 18, 53, 288000)),
        ),
    ]
