# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 03:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160428_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 11, 41, 8, 76000)),
        ),
    ]
