# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 04:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160519_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 12, 43, 30, 245000)),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
