# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160519_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 28, 22, 32, 25, 525535)),
        ),
    ]
